//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ICrawler", CallbackContract=typeof(TestClient.ServiceReference1.ICrawlerCallback))]
    public interface ICrawler {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrawler/DoWork", ReplyAction="http://tempuri.org/ICrawler/DoWorkResponse")]
        void DoWork(string msg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrawler/DoWork", ReplyAction="http://tempuri.org/ICrawler/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync(string msg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrawler/OpenSession", ReplyAction="http://tempuri.org/ICrawler/OpenSessionResponse")]
        void OpenSession();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrawler/OpenSession", ReplyAction="http://tempuri.org/ICrawler/OpenSessionResponse")]
        System.Threading.Tasks.Task OpenSessionAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICrawlerCallback {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrawler/OnCallBack", ReplyAction="http://tempuri.org/ICrawler/OnCallBackResponse")]
        void OnCallBack(string msg);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICrawlerChannel : TestClient.ServiceReference1.ICrawler, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CrawlerClient : System.ServiceModel.DuplexClientBase<TestClient.ServiceReference1.ICrawler>, TestClient.ServiceReference1.ICrawler {
        
        public CrawlerClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public CrawlerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public CrawlerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public CrawlerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public CrawlerClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void DoWork(string msg) {
            base.Channel.DoWork(msg);
        }
        
        public System.Threading.Tasks.Task DoWorkAsync(string msg) {
            return base.Channel.DoWorkAsync(msg);
        }
        
        public void OpenSession() {
            base.Channel.OpenSession();
        }
        
        public System.Threading.Tasks.Task OpenSessionAsync() {
            return base.Channel.OpenSessionAsync();
        }
    }
}
